// src/components/settings/payment/providerDefs.ts
import type { ProviderDef } from "./types";

export const PAYMENT_PROVIDER_DEFS: ProviderDef[] = [
  {
    provider: "bkash",
    title: "bKash",
    category: "Mobile Banking",
    logoText: "bK",
    common: {
      gateway_name: "BKASH_GATEWAY_NAME",
      type: "BKASH_TYPE",
      note: "BKASH_NOTE",
      env: "BKASH_ENV",
    },
    fields: [
      {
        key: "base_url",
        label: "Base URL",
        type: "url",
        required: true,
        placeholder: "https://tokenized.sandbox.bka.sh/...",
        readFromConfigKey: "BKASH_BASE_URL",
      },
      {
        key: "username",
        label: "Username",
        type: "text",
        required: true,
        placeholder: "sandboxTokenizedUser02",
        readFromConfigKey: "BKASH_USERNAME",
      },
      {
        key: "password",
        label: "Password",
        type: "password",
        required: true,
        placeholder: "••••••••",
        readFromConfigKey: "BKASH_PASSWORD",
      },
      {
        key: "app_key",
        label: "App Key",
        type: "text",
        required: true,
        placeholder: "Your app key",
        readFromConfigKey: "BKASH_APP_KEY",
      },
      {
        key: "app_secret",
        label: "App Secret",
        type: "password",
        required: true,
        placeholder: "Your app secret",
        readFromConfigKey: "BKASH_APP_SECRET",
      },
    ],
  },

  {
    provider: "sslcommerz",
    title: "SSLCommerz",
    category: "Payment Gateway",
    logoText: "SC",
    common: {
      gateway_name: "SSL_GATEWAY_NAME",
      type: "SSL_TYPE",
      note: "SSL_NOTE",
      env: "SSL_ENV",
    },
    fields: [
      {
        key: "store_id",
        label: "Store ID",
        type: "text",
        required: true,
        placeholder: "heart63b2e486274af",
        readFromConfigKey: "SSL_STORE_ID",
      },
      {
        key: "store_password",
        label: "Store Password",
        type: "password",
        required: true,
        placeholder: "••••••••",
        readFromConfigKey: "SSL_STORE_PASS",
      },
      {
        key: "base_url",
        label: "Base URL",
        type: "url",
        required: true,
        placeholder: "https://sandbox.sslcommerz.com",
        readFromConfigKey: "SSL_BASE_URL",
      },

      {
        key: "success_url",
        label: "Success URL",
        type: "url",
        placeholder: "https://yourdomain.com/payment/success",
        readFromConfigKey: "SSL_SUCCESS_URL",
      },
      {
        key: "fail_url",
        label: "Fail URL",
        type: "url",
        placeholder: "https://yourdomain.com/payment/fail",
        readFromConfigKey: "SSL_FAIL_URL",
      },
      {
        key: "cancel_url",
        label: "Cancel URL",
        type: "url",
        placeholder: "https://yourdomain.com/payment/cancel",
        readFromConfigKey: "SSL_CANCEL_URL",
      },
      {
        key: "ipn_url",
        label: "IPN URL",
        type: "url",
        placeholder: "https://yourdomain.com/api/v1/payment/ipn",
        readFromConfigKey: "SSL_IPN_URL",
      },
    ],
  },

  {
    provider: "shurjopay",
    title: "ShurjoPay",
    category: "Payment Gateway",
    logoText: "SP",
    common: {
      gateway_name: "SHURJOPAY_GATEWAY_NAME",
      type: "SHURJOPAY_TYPE",
      note: "SHURJOPAY_NOTE",
      env: "SHURJOPAY_ENV",
    },
    fields: [
      {
        key: "base_url",
        label: "Base URL",
        type: "url",
        required: true,
        placeholder: "https://sandbox.shurjopayment.com",
        readFromConfigKey: "SHURJOPAY_BASE_URL",
      },
      {
        key: "username",
        label: "Username",
        type: "text",
        required: true,
        placeholder: "sp_user",
        readFromConfigKey: "SHURJOPAY_USERNAME",
      },
      {
        key: "password",
        label: "Password",
        type: "password",
        required: true,
        placeholder: "••••••••",
        readFromConfigKey: "SHURJOPAY_PASSWORD",
      },
      {
        key: "prefix",
        label: "Prefix",
        type: "text",
        required: true,
        placeholder: "NOB",
        readFromConfigKey: "SHURJOPAY_PREFIX",
      },
      {
        key: "client_ip",
        label: "Client IP",
        type: "text",
        placeholder: "127.0.0.1",
        readFromConfigKey: "SHURJOPAY_CLIENT_IP",
      },
    ],
  },

  {
    provider: "nagad",
    title: "Nagad",
    category: "Mobile Banking",
    logoText: "N",
    common: {
      gateway_name: "NAGAD_GATEWAY_NAME",
      type: "NAGAD_TYPE",
      note: "NAGAD_NOTE",
      env: "NAGAD_ENV",
    },
    fields: [
      {
        key: "merchant_id",
        label: "Merchant ID",
        type: "text",
        required: true,
        placeholder: "6830020071042",
        readFromConfigKey: "NAGAD_MERCHANT_ID",
      },
      {
        key: "base_url",
        label: "Base URL",
        type: "url",
        required: true,
        placeholder: "http://sandbox.mynagad.com:10080/...",
        readFromConfigKey: "NAGAD_BASE_URL",
      },
      {
        key: "public_key",
        label: "Public Key",
        type: "text",
        required: true,
        placeholder: "-----BEGIN PUBLIC KEY----- ...",
        readFromConfigKey: "NAGAD_PUB_KEY",
      },
      {
        key: "private_key",
        label: "Private Key",
        type: "password",
        required: true,
        placeholder: "-----BEGIN RSA PRIVATE KEY----- ...",
        readFromConfigKey: "NAGAD_PRIV_KEY",
      },
    ],
  },

  {
    provider: "rocket",
    title: "Rocket",
    category: "Manual",
    logoText: "R",
    common: {
      gateway_name: "ROCKET_GATEWAY_NAME",
      type: "ROCKET_TYPE",
      note: "ROCKET_NOTE",
      env: "ROCKET_ENV",
    },
    fields: [
      {
        key: "rocket_acc_no",
        label: "Account No",
        type: "text",
        required: true,
        placeholder: "017XXXXXXXX7",
        readFromConfigKey: "ROCKET_ACC_NO",
      },
      {
        key: "rocket_acc_name",
        label: "Account Name",
        type: "text",
        required: true,
        placeholder: "E-Shop Bangladesh",
        readFromConfigKey: "ROCKET_ACC_NAME",
      },
      {
        key: "rocket_bank_name",
        label: "Bank Name",
        type: "text",
        placeholder: "Dutch Bangla Bank",
        readFromConfigKey: "ROCKET_BANK_NAME",
      },
      {
        key: "rocket_suggestion",
        label: "Suggestion",
        type: "text",
        placeholder: "Please enter trx id after send money",
        readFromConfigKey: "ROCKET_SUGGESTION",
      },
    ],
  },

  // ✅ ONLY ADD: COD
  {
    provider: "cod",
    title: "Cash on Delivery",
    category: "Cash",
    logoText: "CD",
    common: {
      // for card name reading
      gateway_name: "CASH_ON_DELIVERY",
      type: "",
      note: "",
      env: "",
    },
    fields: [],
  },
];
