import type { FooterSettings } from "./types";

export const INITIAL_FOOTER_SETTINGS: FooterSettings = {
  theme: "auto",
  layout: {
    maxWidth: "2xl",
    showDivider: true,
  },
  branding: {
    enabled: true,
    logoUrl: "/logo.png",
    brandName: "Graduate Shop",
    tagline: "Quality products, fast delivery, trusted service.",
  },
  columns: [
    {
      id: "col-1",
      title: "Company",
      type: "links",
      enabled: true,
      priority: "High",
      links: [
        {
          id: "l-1",
          label: "About Us",
          href: "/about",
          isExternal: false,
          enabled: true,
          priority: "High",
        },
        {
          id: "l-2",
          label: "Careers",
          href: "/career",
          isExternal: false,
          enabled: true,
          priority: "Normal",
        },
        {
          id: "l-3",
          label: "Contact",
          href: "/contact",
          isExternal: false,
          enabled: true,
          priority: "Normal",
        },
      ],
    },
    {
      id: "col-2",
      title: "Help",
      type: "links",
      enabled: true,
      priority: "High",
      links: [
        {
          id: "l-4",
          label: "Shipping Policy",
          href: "/shipping-policy",
          isExternal: false,
          enabled: true,
          priority: "Normal",
        },
        {
          id: "l-5",
          label: "Return & Refund",
          href: "/return-refund",
          isExternal: false,
          enabled: true,
          priority: "Normal",
        },
        {
          id: "l-6",
          label: "FAQ",
          href: "/faq",
          isExternal: false,
          enabled: true,
          priority: "Normal",
        },
      ],
    },
    {
      id: "col-3",
      title: "Contact",
      type: "contact",
      enabled: true,
      priority: "High",
      contactAddress: "House 29, Road 05, Sector 11, Uttara, Dhaka 1230",
      contactPhones: ["+8801970680283"],
      contactEmails: ["graduatefashion2020@gmail.com"],
    },
    {
      id: "col-4",
      title: "About",
      type: "text",
      enabled: true,
      priority: "Medium",
      text: "We provide premium products with customer-first support. Shop confidently with fast delivery across Bangladesh.",
    },
  ],
  socials: [
    { key: "facebook", label: "Facebook", url: "", enabled: true, priority: "High" },
    { key: "instagram", label: "Instagram", url: "", enabled: true, priority: "High" },
    { key: "whatsapp", label: "WhatsApp", url: "", enabled: true, priority: "Medium" },
    { key: "tiktok", label: "TikTok", url: "", enabled: false, priority: "Low" },
    { key: "youtube", label: "YouTube", url: "", enabled: false, priority: "Low" },
    { key: "x", label: "X", url: "", enabled: false, priority: "Low" },
    { key: "linkedin", label: "LinkedIn", url: "", enabled: false, priority: "Low" },
  ],
  newsletter: {
    enabled: true,
    title: "Join our newsletter",
    description: "Get updates on new arrivals, offers and exclusive deals.",
    placeholder: "Enter your email",
    buttonLabel: "Subscribe",
  },
  payments: {
    enabled: true,
    title: "We Accept",
    icons: [
      { id: "p-1", label: "bKash", imageUrl: "/payments/bkash.png", enabled: true },
      { id: "p-2", label: "Nagad", imageUrl: "/payments/nagad.png", enabled: true },
      { id: "p-3", label: "Visa", imageUrl: "/payments/visa.png", enabled: true },
      { id: "p-4", label: "Mastercard", imageUrl: "/payments/mastercard.png", enabled: true },
    ],
  },
  legal: {
    enabled: true,
    copyrightText: "© {year} Graduate Shop. All rights reserved.",
    showPolicies: true,
    policies: [
      {
        id: "pl-1",
        label: "Privacy Policy",
        href: "/privacy-policy",
        isExternal: false,
        enabled: true,
        priority: "Normal",
      },
      {
        id: "pl-2",
        label: "Terms of Service",
        href: "/terms",
        isExternal: false,
        enabled: true,
        priority: "Normal",
      },
    ],
  },
};
