import Input from "@/components/form/input/InputField";
import Section from "./Section";
import Select from "@/components/form/Select";
import FieldGroup from "@/components/ui/layout/FieldGroup";
import { Package } from "lucide-react";
import { useTranslation } from "react-i18next";

type Option = { value: string; label: string; status?: boolean };

function BasicSection({
  productName,
  setProductName,
  productNameBd,
  setProductNameBd,
  productSlug,
  mainCategoryId,
  setMainCategoryId,
  subCategoryId,
  setSubCategoryId,
  childCategoryId,
  setChildCategoryId,
  brandId,
  setBrandId,

  mainOptions,
  subOptions,
  childOptions,
  brandOptions,

  subLoading,
  childLoading,
}: {
  productName: string;
  setProductName: (v: string) => void;
  productNameBd: string;
  setProductNameBd: (v: string) => void;
  productSlug: string;

  mainCategoryId: number;
  setMainCategoryId: (n: number) => void;
  subCategoryId: number;
  setSubCategoryId: (n: number) => void;
  childCategoryId: number;
  setChildCategoryId: (n: number) => void;
  brandId: number;
  setBrandId: (n: number) => void;

  mainOptions: Option[];
  subOptions: Option[];
  childOptions: Option[];
  brandOptions: Option[];

  subLoading: boolean;
  childLoading: boolean;
}) {
  const { t } = useTranslation();
  return (
    <Section
      title={t("products.createProduct.basicInfoTitle")}
      description={t("products.createProduct.basicInfoDesc")}
      icon={<Package className="h-5 w-5" />}
    >
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <FieldGroup label={t("products.createProduct.productNameLabel")} required>
          <Input
            value={productName}
            onChange={(e) => setProductName(String(e.target.value))}
            placeholder={t("products.createProduct.enterProductName")}
          />
        </FieldGroup>

        <FieldGroup
          label="বাংলা নাম"
          hint="ঐচ্ছিক — বাংলা নাম না দিলে ইংরেজি নাম দেখাবে"
        >
          <Input
            value={productNameBd}
            onChange={(e) => setProductNameBd(String(e.target.value))}
            placeholder="পণ্যের বাংলা নাম লিখুন"
          />
        </FieldGroup>

        <FieldGroup label={t("products.createProduct.slugLabel")}>
          <Input value={productSlug} disabled placeholder={t("products.createProduct.autoGeneratedSlug")} />
        </FieldGroup>

        <FieldGroup label={t("products.createProduct.mainCategoryLabel")} required>
          <Select
            options={mainOptions}
            placeholder={t("products.createProduct.selectMainCategory")}
            value={String(mainCategoryId)}
            onChange={(v) => setMainCategoryId(Number(v))}
          />
        </FieldGroup>

        <FieldGroup label={t("products.createProduct.subCategoryLabel")} required>
          <Select
            key={`sub-${mainCategoryId}-${subCategoryId}`}
            options={subOptions}
            placeholder={
              subLoading
                ? t("products.createProduct.loadingSub")
                : t("products.createProduct.selectSubCategory")
            }
            value={String(subCategoryId)}
            onChange={(v) => setSubCategoryId(Number(v))}
          />
        </FieldGroup>

        <FieldGroup label={t("products.createProduct.childCategoryLabel")}>
          <Select
            key={`child-${subCategoryId}-${childCategoryId}`}
            options={childOptions}
            placeholder={
              !subCategoryId
                ? t("products.createProduct.selectSubFirst")
                : childLoading
                  ? t("products.createProduct.loadingChild")
                  : t("products.createProduct.selectChildCategory")
            }
            value={String(childCategoryId)}
            onChange={(v) => setChildCategoryId(Number(v))}
          />
        </FieldGroup>

        <FieldGroup label={t("products.createProduct.brandLabel")} required>
          <Select
            options={brandOptions}
            placeholder={t("products.createProduct.selectBrand")}
            value={String(brandId)}
            onChange={(v) => setBrandId(Number(v))}
          />
        </FieldGroup>
      </div>
    </Section>
  );
}

export default BasicSection;
