const fs = require('fs');
const path = require('path');
const { createZipBuffer } = require('./zip');
const { randomToken } = require('../../utils/crypto');
const { resolveProductImages, parseDeployConfig } = require('./productImages');

const TEMPLATE_DIR = path.resolve(
  __dirname,
  '../../../../deploy/installer-template'
);

const REGISTRY = process.env.TRIAL_REGISTRY || 'registry.trialvo.com';
const CP_URL = require('../../config/publicUrls').getPublicApiUrl();

function readTemplate(name) {
  return fs.readFileSync(path.join(TEMPLATE_DIR, name), 'utf8');
}

function envExampleForMode(mode = 'trial') {
  const base = readTemplate('.env.example');
  const trialMode = mode === 'paid' ? '0' : '1';
  if (/^TRIAL_MODE=/m.test(base)) {
    return base.replace(/^TRIAL_MODE=.*$/m, `TRIAL_MODE=${trialMode}`);
  }
  return `${base.trimEnd()}\n\nTRIAL_MODE=${trialMode}\n`;
}

/**
 * Load the license public key so the client's API can verify signed leases.
 * Mirrors provisioner.loadLicensePublicKey — env first, then deploy/keys.
 */
function loadLicensePublicKey() {
  if (process.env.LICENSE_PUBLIC_KEY) return process.env.LICENSE_PUBLIC_KEY;
  const candidates = [
    path.resolve(__dirname, '../../../deploy/keys/license_public.pem'),
    path.resolve(__dirname, '../../../../deploy/keys/license_public.pem'),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8');
  }
  return '';
}

/**
 * Create scoped registry credentials for this trial instance.
 * Real registry ACL is ops-side; we issue/revoke tokens in instance meta.
 */
function issueRegistryCredentials({ installId, expiresAt }) {
  const token = randomToken(32);
  const user = `trial-${installId.slice(0, 8)}`;
  return {
    registry: REGISTRY,
    user,
    token,
    expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null,
    revoked: false,
  };
}

function buildAgentEnv({
  installId,
  agentSecret,
  bootstrapToken,
  domain,
  backupKey,
  registryCreds,
  controlPlaneUrl = CP_URL,
  adminEmail = '',
  adminPassword = '',
  /** trial | paid */
  mode = 'trial',
  /** When true (cPanel), skip Go gate — Node refreshes lease in-process. */
  nodeOnly = false,
  productSlug = 'lifestyle-ecommerce',
  deployConfig = null,
}) {
  const isPaid = mode === 'paid';
  const images = resolveProductImages({
    productSlug,
    deployConfig,
    registry: registryCreds?.registry || REGISTRY,
  });

  const lines = [
    `# Generated by Trialvo packager — do not commit`,
    `CONTROL_PLANE_URL=${controlPlaneUrl}`,
    `TRIAL_INSTALL_ID=${installId}`,
    `TRIAL_AGENT_SECRET=${agentSecret}`,
    `TRIAL_BOOTSTRAP_TOKEN=${bootstrapToken}`,
    `TRIAL_DOMAIN=${domain || ''}`,
    isPaid ? `TRIAL_MODE=0` : `TRIAL_MODE=1`,
    isPaid ? `LICENSE_ENFORCE=1` : `LICENSE_ENFORCE=0`,
    `TRIAL_BACKUP_KEY=${backupKey || ''}`,
    `TRIAL_ADMIN_EMAIL=${adminEmail || ''}`,
    // Password lives in customer .env / email — not in agent.env (reduces ZIP blast radius)
    `TRIAL_ADMIN_PASSWORD=`,
    `PRODUCT_CODE=${images.prefix}`,
    `AGENT_HEARTBEAT_MS=${process.env.AGENT_HEARTBEAT_MS || '600000'}`,
    `AGENT_LEASE_MS=1800000`,
  ];

  if (registryCreds) {
    lines.push(
      `TRIAL_REGISTRY=${registryCreds.registry}`,
      `TRIAL_REGISTRY_USER=${registryCreds.user}`,
      `TRIAL_REGISTRY_TOKEN=${registryCreds.token}`,
      `TRIAL_IMAGE_API=${images.api}`,
      `TRIAL_IMAGE_ADMIN=${images.admin}`,
      `TRIAL_IMAGE_SHOP=${images.shop}`,
      `TRIAL_IMAGE_AGENT=${images.agent}`
    );
  }

  if (nodeOnly) {
    lines.push(`USE_AGENT_GATE=0`, `# cPanel / Node-only — lease via Control Plane directly`);
  } else {
    lines.push(
      `USE_AGENT_GATE=1`,
      `AGENT_GATE_URL=http://license-agent:9099/gate`,
      `AGENT_PORT=9099`
    );
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Build downloadable Opt2 installer ZIP (plan §10.1).
 * @returns {{ buffer: Buffer, filename: string, files: string[] }}
 */
function buildInstallerZip(ctx) {
  const images = resolveProductImages({
    productSlug: ctx.productSlug,
    deployConfig: ctx.deployConfig,
    registry: ctx.registryCreds?.registry || REGISTRY,
  });
  const root = `trialvo-${images.packLabel}-trial`;
  const agentEnv = buildAgentEnv({ ...ctx, mode: 'trial', nodeOnly: false });
  const title = images.packLabel.replace(/-/g, ' ');
  const readme = [
    `# Trialvo ${title} Trial (Option 2)`,
    '',
    'Full walkthrough: open INSTALL.md in this folder (VPS / Docker).',
    'cPanel / Node packs: see INSTALL-CPANEL.md instead.',
    '',
    '1. Unzip on your VPS. Prerequisites: Docker + Compose, DNS A record, ports 80/443.',
    '2. Copy `.env.example` → `.env` — set DOMAIN, DB password, PUBLIC_* origins,',
    '   and TRIAL_ADMIN_EMAIL / TRIAL_ADMIN_PASSWORD from your Trialvo status email.',
    '3. Keep `agent.env` as shipped. Do not share it.',
    '4. Run `chmod +x setup.sh && ./setup.sh` (Linux/macOS) or `./setup.ps1` (Windows).',
    '5. First run may only create `.env` — edit it, then re-run setup.',
    '6. Point DNS at this host; wait for containers; open shop + admin URLs.',
    '7. The license agent registers with Trialvo; the status page becomes Active.',
    '',
    'If something fails: `docker compose ps` / `docker compose logs`.',
    'The VPS must reach CONTROL_PLANE_URL. Installer links are single-use.',
    '',
    'Services: api, admin, shop, db (mysql:8.0), license-agent (Go lease gate).',
    '',
    `Product: ${ctx.productSlug || images.prefix}`,
    `Install ID: ${ctx.installId}`,
    `Control plane: ${ctx.controlPlaneUrl || CP_URL}`,
    '',
    'See INSTALL.md and TRIAL_TERMS.md.',
    '',
  ].join('\n');

  const entries = [
    { name: `${root}/docker-compose.yml`, data: readTemplate('docker-compose.yml') },
    { name: `${root}/setup.sh`, data: readTemplate('setup.sh').replace(/\r\n/g, '\n') },
    { name: `${root}/setup.ps1`, data: readTemplate('setup.ps1') },
    { name: `${root}/.env.example`, data: envExampleForMode('trial') },
    { name: `${root}/TRIAL_TERMS.md`, data: readTemplate('TRIAL_TERMS.md') },
    { name: `${root}/INSTALL.md`, data: readTemplate('INSTALL.md') },
    { name: `${root}/INSTALL-CPANEL.md`, data: readTemplate('INSTALL-CPANEL.md') },
    { name: `${root}/agent.env`, data: agentEnv },
    { name: `${root}/license_public.pem`, data: ctx.licensePublicKey || loadLicensePublicKey() },
    { name: `${root}/README.md`, data: readme },
  ];

  const buffer = createZipBuffer(entries);
  const filename = `trialvo-${images.packLabel}-trial-${ctx.installId.slice(0, 12)}.zip`;
  return { buffer, filename, files: entries.map((e) => e.name) };
}

/**
 * Paid Docker pack — same compose as trial, LICENSE_ENFORCE=1 (no TRIAL_MODE).
 */
function buildPaidDockerZip(ctx) {
  const images = resolveProductImages({
    productSlug: ctx.productSlug,
    deployConfig: ctx.deployConfig,
    registry: ctx.registryCreds?.registry || REGISTRY,
  });
  const root = `trialvo-${images.packLabel}-paid`;
  const registryCreds = ctx.registryCreds || issueRegistryCredentials({
    installId: ctx.installId,
    expiresAt: ctx.expiresAt,
  });
  const agentEnv = buildAgentEnv({
    ...ctx,
    registryCreds,
    mode: 'paid',
    nodeOnly: false,
  });
  const title = images.packLabel.replace(/-/g, ' ');
  const readme = [
    `# Trialvo ${title} — Licensed Docker deployment`,
    '',
    'This pack is bound to your purchase. Do not share agent.env.',
    'Copying to another domain without a domain transfer will freeze the license.',
    'Full walkthrough: INSTALL.md in this folder.',
    '',
    '1. Copy `.env.example` → `.env` — DOMAIN, passwords, PUBLIC_* URLs, admin email/password.',
    '2. Keep `agent.env` as shipped (LICENSE_ENFORCE=1, TRIAL_MODE=0).',
    '3. `chmod +x setup.sh && ./setup.sh` (or setup.ps1). First run may only create `.env`.',
    '4. Point DNS at this host. Wait for containers; open shop + admin.',
    '5. The agent registers with Trialvo on first boot.',
    '',
    `Product: ${ctx.productSlug || images.prefix}`,
    `Install ID: ${ctx.installId}`,
    `Control plane: ${ctx.controlPlaneUrl || CP_URL}`,
    '',
  ].join('\n');

  const entries = [
    { name: `${root}/docker-compose.yml`, data: readTemplate('docker-compose.yml') },
    { name: `${root}/setup.sh`, data: readTemplate('setup.sh').replace(/\r\n/g, '\n') },
    { name: `${root}/setup.ps1`, data: readTemplate('setup.ps1') },
    { name: `${root}/.env.example`, data: envExampleForMode('paid') },
    { name: `${root}/INSTALL.md`, data: readTemplate('INSTALL.md') },
    { name: `${root}/agent.env`, data: agentEnv },
    { name: `${root}/license_public.pem`, data: ctx.licensePublicKey || loadLicensePublicKey() },
    { name: `${root}/README.md`, data: readme },
  ];

  const buffer = createZipBuffer(entries);
  const filename = `trialvo-${images.packLabel}-paid-docker-${ctx.installId.slice(0, 12)}.zip`;
  return { buffer, filename, files: entries.map((e) => e.name), registryCreds };
}

/**
 * cPanel / shared-host pack — Node-only license client (no Docker / Go sidecar).
 * Customer uploads API build separately; this ZIP carries license.env + docs.
 */
function buildPaidCpanelZip(ctx) {
  const images = resolveProductImages({
    productSlug: ctx.productSlug,
    deployConfig: ctx.deployConfig,
    registry: REGISTRY,
  });
  const root = `trialvo-${images.packLabel}-cpanel`;
  const licenseEnv = buildAgentEnv({
    ...ctx,
    registryCreds: null,
    mode: 'paid',
    nodeOnly: true,
  });
  const title = images.packLabel.replace(/-/g, ' ');

  const readme = [
    `# Trialvo ${title} — cPanel / Node hosting pack`,
    '',
    'For Passenger / CloudLinux Node or similar shared hosting.',
    '',
    '1. Deploy the product API (Node) to your cPanel Node app.',
    '2. Place `license.env` next to the app and load it at boot',
    '   (dotenv / PassengerEnvVar / export in startup script).',
    '3. Copy `license_public.pem` to `config/license_public.pem` on the API.',
    '4. Set TRIAL_DOMAIN to the exact public hostname customers will use.',
    '5. Restart the Node app — it registers with Trialvo (LICENSE_ENFORCE=1).',
    '',
    'No Docker or Go license-agent is required; the API phones home directly.',
    'Copying this license.env to another domain will trigger a domain conflict freeze.',
    '',
    `Product: ${ctx.productSlug || images.prefix}`,
    `Install ID: ${ctx.installId}`,
    `Control plane: ${ctx.controlPlaneUrl || CP_URL}`,
    '',
    'Admin / Shop frontends: build statically and point API_ORIGIN at this API.',
    '',
    'See INSTALL-CPANEL.md for the full cPanel / Node checklist.',
    '',
  ].join('\n');

  const passengerNote = [
    '# Example Passenger / Node startup snippet',
    '# Load license.env before requiring the app:',
    "require('dotenv').config({ path: __dirname + '/license.env' });",
    "require('./index.js');",
    '',
  ].join('\n');

  const entries = [
    { name: `${root}/license.env`, data: licenseEnv },
    { name: `${root}/license_public.pem`, data: ctx.licensePublicKey || loadLicensePublicKey() },
    { name: `${root}/passenger-startup.example.js`, data: passengerNote },
    { name: `${root}/INSTALL-CPANEL.md`, data: readTemplate('INSTALL-CPANEL.md') },
    { name: `${root}/README.md`, data: readme },
  ];

  const buffer = createZipBuffer(entries);
  const filename = `trialvo-${images.packLabel}-cpanel-${ctx.installId.slice(0, 12)}.zip`;
  return { buffer, filename, files: entries.map((e) => e.name) };
}

/**
 * Trial self-hosted pack for Node/cPanel products (no Docker / Go license-agent).
 */
function buildTrialCpanelZip(ctx) {
  const images = resolveProductImages({
    productSlug: ctx.productSlug,
    deployConfig: ctx.deployConfig,
    registry: REGISTRY,
  });
  const root = `trialvo-${images.packLabel}-trial-cpanel`;
  const licenseEnv = buildAgentEnv({
    ...ctx,
    registryCreds: null,
    mode: 'trial',
    nodeOnly: true,
  });
  const title = images.packLabel.replace(/-/g, ' ');

  const readme = [
    `# Trialvo ${title} — Trial (Option 2, cPanel / Node)`,
    '',
    'For Passenger / CloudLinux Node or VPS Node hosting.',
    '',
    '1. Deploy `my-shop-api` as your Node app (see product README).',
    '2. Build `my-shop-admin` (Vite) and `my-shop-shop` (Next standalone) — point API URLs at your API.',
    '3. Place `license.env` next to the API and load at boot.',
    '4. Copy `license_public.pem` to API `config/` if required by your build.',
    '5. Set TRIAL_DOMAIN to your public hostname and restart.',
    '',
    `Product: ${ctx.productSlug || images.prefix}`,
    `Install ID: ${ctx.installId}`,
    `Control plane: ${ctx.controlPlaneUrl || CP_URL}`,
    '',
    'See INSTALL-CPANEL.md for the full cPanel / Node checklist.',
    '',
  ].join('\n');

  const entries = [
    { name: `${root}/license.env`, data: licenseEnv },
    { name: `${root}/license_public.pem`, data: ctx.licensePublicKey || loadLicensePublicKey() },
    { name: `${root}/INSTALL-CPANEL.md`, data: readTemplate('INSTALL-CPANEL.md') },
    { name: `${root}/README.md`, data: readme },
  ];

  const buffer = createZipBuffer(entries);
  const filename = `trialvo-${images.packLabel}-trial-cpanel-${ctx.installId.slice(0, 12)}.zip`;
  return { buffer, filename, files: entries.map((e) => e.name) };
}

/**
 * Route trial Option 2 installer to Docker template or Node/cPanel pack.
 */
function buildTrialInstallerZip(ctx) {
  const dc = parseDeployConfig(ctx.deployConfig);
  if (ctx.hostKind === 'cpanel' || dc.installer_mode === 'node_only') {
    return buildTrialCpanelZip(ctx);
  }
  return buildInstallerZip(ctx);
}

module.exports = {
  issueRegistryCredentials,
  buildInstallerZip,
  buildTrialInstallerZip,
  buildTrialCpanelZip,
  buildPaidDockerZip,
  buildPaidCpanelZip,
  buildAgentEnv,
  loadLicensePublicKey,
  resolveProductImages,
  parseDeployConfig,
  TEMPLATE_DIR,
  CP_URL,
};
