/**
 * Catalog card / gallery images for Trialvo shop products.
 * WebP screenshots from product-images/ (served via /uploads/catalog/...).
 */
module.exports = {
  lifestyle: {
    thumbnail: "/uploads/catalog/lifestyle-ecommerce/shop/shop-01.webp",
    shop: [
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-01.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-02.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-03.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-04.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-05.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-06.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-07.webp",
      "/uploads/catalog/lifestyle-ecommerce/shop/shop-08.webp",
    ],
    admin: [
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-01.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-02.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-03.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-04.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-05.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-06.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-07.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-08.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-09.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-10.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-11.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-12.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-13.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-14.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-15.webp",
      "/uploads/catalog/lifestyle-ecommerce/admin/admin-16.webp",
    ],
  },
  fashion: {
    thumbnail: "/uploads/catalog/fashion-ecommerce/shop/shop-01.webp",
    shop: [
      "/uploads/catalog/fashion-ecommerce/shop/shop-01.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-02.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-03.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-04.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-05.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-06.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-07.webp",
      "/uploads/catalog/fashion-ecommerce/shop/shop-08.webp",
    ],
    admin: [
      "/uploads/catalog/fashion-ecommerce/admin/admin-01.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-02.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-03.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-04.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-05.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-06.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-07.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-08.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-09.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-10.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-11.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-12.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-13.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-14.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-15.webp",
      "/uploads/catalog/fashion-ecommerce/admin/admin-16.webp",
    ],
  },
  tech: {
    thumbnail: "/uploads/catalog/tech-shop-ecommerce/shop/shop-01.webp",
    shop: [
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-01.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-02.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-03.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-04.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-05.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-06.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-07.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-08.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-09.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-10.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-11.webp",
      "/uploads/catalog/tech-shop-ecommerce/shop/shop-12.webp",
    ],
    admin: [
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-01.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-02.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-03.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-04.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-05.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-06.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-07.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-08.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-09.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-10.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-11.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-12.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-13.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-14.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-15.webp",
      "/uploads/catalog/tech-shop-ecommerce/admin/admin-16.webp",
    ],
  },
  combobasket: {
    thumbnail: "/uploads/catalog/combo-basket-ecommerce/shop/shop-01.webp",
    shop: [
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-01.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-02.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-03.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-04.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-05.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-06.webp",
      "/uploads/catalog/combo-basket-ecommerce/shop/shop-07.webp",
    ],
    admin: [
      "/uploads/catalog/combo-basket-ecommerce/admin/admin-01.webp",
      "/uploads/catalog/combo-basket-ecommerce/admin/admin-02.webp",
      "/uploads/catalog/combo-basket-ecommerce/admin/admin-03.webp",
      "/uploads/catalog/combo-basket-ecommerce/admin/admin-04.webp",
      "/uploads/catalog/combo-basket-ecommerce/admin/admin-05.webp",
    ],
  },
};
