const fs = require('fs');
const path = require('path');
const { createZipBuffer } = require('./zip');
const { randomToken } = require('../../utils/crypto');

const TEMPLATE_DIR = path.resolve(
  __dirname,
  '../../../../deploy/installer-template'
);

const REGISTRY = process.env.TRIAL_REGISTRY || 'registry.trialvo.com';
const IMAGE_API = process.env.TRIAL_IMAGE_API || `${REGISTRY}/lifestyle-api:trial`;
const IMAGE_ADMIN = process.env.TRIAL_IMAGE_ADMIN || `${REGISTRY}/lifestyle-admin:trial`;
const IMAGE_SHOP = process.env.TRIAL_IMAGE_SHOP || `${REGISTRY}/lifestyle-shop:trial`;
const CP_URL = require('../../config/publicUrls').getPublicApiUrl();

function readTemplate(name) {
  return fs.readFileSync(path.join(TEMPLATE_DIR, name), 'utf8');
}

/**
 * Load the license public key so the client's API can verify signed leases.
 * Mirrors provisioner.loadLicensePublicKey — env first, then deploy/keys.
 */
function loadLicensePublicKey() {
  if (process.env.LICENSE_PUBLIC_KEY) return process.env.LICENSE_PUBLIC_KEY;
  const candidates = [
    path.resolve(__dirname, '../../../deploy/keys/license_public.pem'),
    path.resolve(__dirname, '../../../../deploy/keys/license_public.pem'),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8');
  }
  return '';
}

/**
 * Create scoped registry credentials for this trial instance.
 * Real registry ACL is ops-side; we issue/revoke tokens in instance meta.
 */
function issueRegistryCredentials({ installId, expiresAt }) {
  const token = randomToken(32);
  const user = `trial-${installId.slice(0, 8)}`;
  return {
    registry: REGISTRY,
    user,
    token,
    expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null,
    revoked: false,
  };
}

function buildAgentEnv({
  installId,
  agentSecret,
  bootstrapToken,
  domain,
  backupKey,
  registryCreds,
  controlPlaneUrl = CP_URL,
  adminEmail = '',
  adminPassword = '',
}) {
  const lines = [
    `# Generated by Trialvo packager — do not commit`,
    `CONTROL_PLANE_URL=${controlPlaneUrl}`,
    `TRIAL_INSTALL_ID=${installId}`,
    `TRIAL_AGENT_SECRET=${agentSecret}`,
    `TRIAL_BOOTSTRAP_TOKEN=${bootstrapToken}`,
    `TRIAL_DOMAIN=${domain || ''}`,
    `TRIAL_MODE=1`,
    `TRIAL_BACKUP_KEY=${backupKey || ''}`,
    // Seeded into MySQL by seed-trial-admin.js so emailed credentials work.
    `TRIAL_ADMIN_EMAIL=${adminEmail || ''}`,
    `TRIAL_ADMIN_PASSWORD=${adminPassword || ''}`,
    `TRIAL_REGISTRY=${registryCreds.registry}`,
    `TRIAL_REGISTRY_USER=${registryCreds.user}`,
    `TRIAL_REGISTRY_TOKEN=${registryCreds.token}`,
    `TRIAL_IMAGE_API=${IMAGE_API}`,
    `TRIAL_IMAGE_ADMIN=${IMAGE_ADMIN}`,
    `TRIAL_IMAGE_SHOP=${IMAGE_SHOP}`,
    `TRIAL_IMAGE_AGENT=${process.env.TRIAL_IMAGE_AGENT || `${REGISTRY}/lifestyle-license-agent:trial`}`,
    `USE_AGENT_GATE=1`,
    `AGENT_GATE_URL=http://license-agent:9099/gate`,
    `AGENT_PORT=9099`,
  ];
  return `${lines.join('\n')}\n`;
}

/**
 * Build downloadable Opt2 installer ZIP (plan §10.1).
 * @returns {{ buffer: Buffer, filename: string, files: string[] }}
 */
function buildInstallerZip(ctx) {
  const root = 'trialvo-lifestyle-trial';
  const agentEnv = buildAgentEnv(ctx);
  const readme = [
    '# Trialvo Lifestyle Trial (Option 2)',
    '',
    '1. Edit `.env` (copy from `.env.example`) — set DOMAIN, DB password and the',
    '   PUBLIC_API_ORIGIN / PUBLIC_SHOP_ORIGIN your users will open.',
    '2. Run `chmod +x setup.sh && ./setup.sh` (Linux/macOS) or `./setup.ps1` (Windows).',
    '3. Point DNS for your domain to this host; open the firewall ports from `.env`.',
    '4. First boot seeds the demo data automatically, then the license agent',
    '   registers with Trialvo using the secrets in `agent.env`.',
    '',
    'Services: api, admin, shop, db (mysql:8.0), license-agent (Go lease gate).',
    'The Go license-agent enforces the lease; the API stays locked without it.',
    '',
    `Install ID: ${ctx.installId}`,
    `Control plane: ${ctx.controlPlaneUrl || CP_URL}`,
    '',
    'See TRIAL_TERMS.md.',
    '',
  ].join('\n');

  const entries = [
    { name: `${root}/docker-compose.yml`, data: readTemplate('docker-compose.yml') },
    { name: `${root}/setup.sh`, data: readTemplate('setup.sh').replace(/\r\n/g, '\n') },
    { name: `${root}/setup.ps1`, data: readTemplate('setup.ps1') },
    { name: `${root}/.env.example`, data: readTemplate('.env.example') },
    { name: `${root}/TRIAL_TERMS.md`, data: readTemplate('TRIAL_TERMS.md') },
    { name: `${root}/agent.env`, data: agentEnv },
    // Public key the API uses to verify the signed license lease.
    { name: `${root}/license_public.pem`, data: ctx.licensePublicKey || loadLicensePublicKey() },
    { name: `${root}/README.md`, data: readme },
  ];

  const buffer = createZipBuffer(entries);
  const filename = `trialvo-lifestyle-trial-${ctx.installId.slice(0, 12)}.zip`;
  return { buffer, filename, files: entries.map((e) => e.name) };
}

module.exports = {
  issueRegistryCredentials,
  buildInstallerZip,
  buildAgentEnv,
  loadLicensePublicKey,
  TEMPLATE_DIR,
  CP_URL,
};
