import type { CustomerRow } from "./types";

export const CUSTOMER_ROWS: CustomerRow[] = [
  {
    id: 1,
    email: "nazmul@example.com",
    first_name: "Nazmul",
    last_name: "Hasan",
    name: "Nazmul Hasan",
    img_path: null,
    status: "active",
    gender: "male",
    dob: null,
    is_email_verified: true,
    is_fully_verified: false,
    has_password: true,
    total_spent: 5875,
    phone: "+8801711122233",
    phone_verified: true,
    created_at: "2025-06-10T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 2,
    email: "rooney@example.com",
    first_name: "Rooney",
    last_name: "Hossain",
    name: "Rooney Hossain",
    img_path: null,
    status: "suspended",
    gender: "male",
    dob: null,
    is_email_verified: false,
    is_fully_verified: false,
    has_password: true,
    total_spent: 0,
    phone: "+8801999888777",
    phone_verified: false,
    created_at: "2025-01-10T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 3,
    email: "mehedi@example.com",
    first_name: "Mehedi",
    last_name: "Hossain",
    name: "Mehedi Hossain",
    img_path: null,
    status: "active",
    gender: "male",
    dob: null,
    is_email_verified: true,
    is_fully_verified: true,
    has_password: true,
    total_spent: 990,
    phone: "+8801555444333",
    phone_verified: true,
    created_at: "2025-09-15T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 4,
    email: "fahim@example.com",
    first_name: "Fahim",
    last_name: "Ahmed",
    name: "Fahim Ahmed",
    img_path: null,
    status: "active",
    gender: "male",
    dob: null,
    is_email_verified: true,
    is_fully_verified: true,
    has_password: true,
    total_spent: 5300,
    phone: "+8801999777666",
    phone_verified: true,
    created_at: "2025-10-08T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 5,
    email: "shamima@example.com",
    first_name: "Shamima",
    last_name: "Khatun",
    name: "Shamima Khatun",
    img_path: null,
    status: "inactive",
    gender: "female",
    dob: null,
    is_email_verified: false,
    is_fully_verified: false,
    has_password: false,
    total_spent: 1260,
    phone: "+8801400998877",
    phone_verified: false,
    created_at: "2025-08-20T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 6,
    email: "sumaiya@example.com",
    first_name: "Sumaiya",
    last_name: "Akter",
    name: "Sumaiya Akter",
    img_path: null,
    status: "inactive",
    gender: "female",
    dob: null,
    is_email_verified: false,
    is_fully_verified: false,
    has_password: false,
    total_spent: 1800,
    phone: "+8801788776655",
    phone_verified: false,
    created_at: "2025-08-01T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 7,
    email: "sabbir@example.com",
    first_name: "Sabbir",
    last_name: "Rahman",
    name: "Sabbir Rahman",
    img_path: null,
    status: "suspended",
    gender: "male",
    dob: null,
    is_email_verified: false,
    is_fully_verified: false,
    has_password: true,
    total_spent: 420,
    phone: "+8801912345678",
    phone_verified: false,
    created_at: "2025-07-18T00:00:00Z",
    deleted_at: null,
    isDeleted: false,
  },
  {
    id: 8,
    email: "tanvir@example.com",
    first_name: "Tanvir",
    last_name: "Islam",
    name: "Tanvir Islam",
    img_path: null,
    status: "suspended",
    gender: "male",
    dob: null,
    is_email_verified: false,
    is_fully_verified: false,
    has_password: true,
    total_spent: 2500,
    phone: "+8801611122211",
    phone_verified: false,
    created_at: "2025-06-05T00:00:00Z",
    deleted_at: "2025-09-01T00:00:00Z",
    isDeleted: true,
  },
];
